services:  
  minecraft-bot:
    build:
      context: .
    env_file: .env
    environment:
      NODE_ENV: production
      BOT_PORT: 25565
      BOX_WIDTH: 800
      BOX_CENTER_X: 0
      BOX_CENTER_Z: 0
      RESPONSE_METRIC: true
      RESPONSE_INTERVAL: 1000
    deploy:
      replicas: 1
    ports:
      - "9090:9090"
